name: mt_learning
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.6
  - pytorch>=1.3.0
  - torchvision
  - keras=2.3.1
  - tensorflow=2.0
  - scikit-learn
  - numpy
  - scipy
  - pandas
  - matplotlib==3.1.0
  - pip
